== Advanced Usage

[[performance-tool-retention]]
=== Retention

If you run performance tests for a long time, you might be interested in setting
a https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#limiting-the-size-of-a-stream[retention strategy] for
the streams the performance tool creates for a run. This
would typically avoid saturating the storage devices of your servers.
The default values are 20 GB for the maximum size of a stream and
500 MB for each segment files that composes a stream. You can change
these values with the `--max-length-bytes` and `--stream-max-segment-size-bytes` options:

----
java -jar stream-perf-test.jar --max-length-bytes 10gb \
                               --stream-max-segment-size-bytes 250mb
----

Both options accept units (`kb`, `mb`, `gb`, `tb`), as well as no unit to
specify a number of bytes.

It is also possible to use the time-based retention strategy with the `--max-age` option.
This can be less predictable than `--max-length-bytes` in the context of performance tests though.
The following command shows how to set the maximum age of segments to 5 minutes with
a maximum segment size of 250 MB:

----
java -jar stream-perf-test.jar --max-age PT5M \
                               --stream-max-segment-size-bytes 250mb
----

The `--max-age` option uses the
https://en.wikipedia.org/wiki/ISO_8601#Durations[ISO 8601 duration format].

=== Offset (Consumer)

Consumers start by default at the very end of a stream (offset `next`).
It is possible to specify an https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#specifying-an-offset[offset]
to start from with the `--offset` option,
if you have existing streams, and you want to consume from them at a specific offset.
The following command sets the consumer to start consuming at the beginning of
a stream:

----
java -jar stream-perf-test.jar --offset first
----

The accepted values for `--offset` are `first`, `last`, `next` (the default),
an unsigned long for a given offset, and an ISO 8601 formatted timestamp
(eg. `2020-06-03T07:45:54Z`).

[[performance-tool-offset-tracking]]
=== Offset Tracking (Consumer)

A consumer can https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#consumer-offset-tracking[track the point] it has reached
in a stream to be able to restart where it left off in a new incarnation.
The performance tool has the `--store-every` option to tell consumers to store
the offset every `x` messages to be able to measure the impact of offset tracking
in terms of throughput and storage. This feature is disabled by default.
The following command shows how to store the offset every 100,000 messages:

----
java -jar stream-perf-test.jar --store-every 100000
----

[[consumer-names]]
=== Consumer Names

When using `--store-every` (see above) for https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#consumer-offset-tracking[offset tracking],
the performance tool uses a default name using the pattern `{stream-name}-{consumer-number}`.
So the default name of a single tracking consumer consuming from `stream` will be `stream-1`.

The consumer names pattern can be set with the `--consumer-names` option, which uses
the https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html[Java printf-style format string].
The stream name and the consumer number are injected as arguments, in this order.

The following table illustrates some examples for the `--consumer-names` option
for a `s1` stream and a second consumer:

[%header,cols=3*]
|===
|Option
|Computed Name
|Details

|`%s-%d`
|`s1-2`
|Default pattern.

|`stream-%s-consumer-%d`
|`stream-s1-consumer-2`
|

|`consumer-%2$d-on-stream-%1$s`
|`consumer-2-on-stream-s1`
|The argument indexes (`1$` for the stream, `2$` for the consumer number) must be used
as the pattern uses the consumer number first, which is not the pre-defined order of arguments.

|`uuid`
|`7cc75659-ea67-4874-96ef-151a505e1a55`
|https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()[Random UUID] that
changes for every run.
|===

Note you can use `--consumer-names uuid` to change the consumer names for every run. This
can be useful when you want to use tracking consumers in different runs but you want to
force the offset they start consuming from. With consumer names that do not change between runs,
tracking consumers would ignore the specified offset and would start where they left off
(this is the purpose of offset tracking).

=== Producer Names

You can use the `--producer-names` option to set the producer names pattern and therefore
enable https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#outbound-message-deduplication[message deduplication] (using the default
publishing sequence starting at 0 and incremented for each message).
The same naming options apply as above in <<consumer-names, consumer names>> with the only
difference that the default pattern is empty (i.e. no deduplication).

Here is an example of the usage of the `--producer-names` option:

----
java -jar stream-perf-test.jar --producer-names %s-%d
----

The run will start one producer and will use the `stream-1` producer reference (default stream is `stream` and the number of the producer is 1.)

=== Load Balancer in Front of the Cluster

A load balancer can misguide the performance tool when it tries to connect to nodes that host stream leaders and replicas.
The https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/["Connecting to Streams"] blog post covers why client applications must connect to the appropriate nodes in a cluster.

Use the `--load-balancer` flag to make sure the performance tool always goes through the load balancer that sits in front of your cluster:

----
java -jar stream-perf-test.jar --uris rabbitmq-stream://my-load-balancer:5552 \
                               --load-balancer
----

The same blog post covers why a https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/#with-a-load-balancer[load balancer can make things more complicated] for client applications like the performance tool and how https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/#client-workaround-with-a-load-balancer[they can mitigate these issues].

[[performance-tool-sac]]
=== Single Active Consumer

If the `--single-active-consumer` flag is set, the performance tool will create https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#single-active-consumer[single active consumer] instances.
This means that if there are more consumers than streams, there will be only one active consumer at a time on a stream, _if they share the same name_.
Note <<performance-tool-offset-tracking, offset tracking>> gets enabled automatically if it's not with `--single-active-consumer` (using 10,000 for `--store-every`).
Let's see a couple of examples.

In the following command we have 1 producer publishing to 1 stream and 3 consumers on this stream.
As `--single-active-consumer` is used, only one of these consumers will be active at a time.

----
java -jar stream-perf-test.jar --producers 1 --consumers 3 --single-active-consumer \
                               --consumer-names my-app
----

Note we use a fixed value for the consumer names: if they don't have the same name, the broker will not consider them as a group of consumers, so they will all get messages, like regular consumers.

In the following example we have 2 producers for 2 streams and 6 consumers overall (3 for each stream).
Note the consumers have the same name on their streams with the use of `--consumer-names my-app-%s`, as `%s` is a <<consumer-names, placeholder for the stream name>>.

----
java -jar stream-perf-test.jar --producers 2 --consumers 6 --stream-count 2 \
                               --single-active-consumer --consumer-names my-app-%s
----


=== Super Streams

The performance tool has a `--super-streams` flag to enable https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#super-streams[super streams] on the publisher and consumer sides.
This support is meant to be used with the <<performance-tool-sac, `--single-active-consumer` flag>>, to https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#super-stream-sac[benefit from both features].
We recommend reading the appropriate sections of the documentation to understand the semantics of the flags before using them.
Let's see some examples.

The example below creates 1 producer and 3 consumers on the default `stream`, which is now a _super stream_ because of the `--super-streams` flag:

----
java -jar stream-perf-test.jar --producers 1 --consumers 3 --single-active-consumer \
                               --super-streams --consumer-names my-app
----

The performance tool creates 3 individual streams by default, they are the partitions of the super stream.
They are named `stream-0`, `stream-1`, and `stream-2`, after the name of the super stream, `stream`.
The producer will publish to each of them, using a https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#super-stream-producer[hash-based routing strategy].

A consumer is _composite_ with `--super-streams`: it creates a consumer instance for each partition.
This is 9 consumer instances overall – 3 composite consumers and 3 partitions – spread evenly across the partitions, but with only one active at a time on a given stream.

Note we use a fixed consumer name so that the broker considers the consumers belong to the same group and enforce the single active consumer behavior.

The next example is more convoluted.
We are going to work with 2 super streams (`--stream-count 2` and `--super-streams`).
Each super stream will have 5 partitions (`--super-stream-partitions 5`), so this is 10 streams overall (`stream-1-0` to `stream-1-4` and `stream-2-0` to `stream-2-4`).
Here is the command line:

----
java -jar stream-perf-test.jar --producers 2 --consumers 6 --stream-count 2 \
                               --super-streams --super-stream-partitions 5 \
                               --single-active-consumer \
                               --consumer-names my-app-%s
----

We see also that each super stream has 1 producer (`--producers 2`) and 3 consumers (`--consumers 6`).
The composite consumers will spread their consumer instances across the partitions.
Each partition will have 3 consumers but only 1 active at a time with `--single-active-consumer` and `--consumer-names my-app-%s` (the consumers on a given stream have the same name, so the broker make sure only one consumes at a time).

Note the performance tool does not use <<common-usage.adoc#performance-tool-connection-pooling, connection pooling>> by default.
The command above opens a significant number of connections – 30 just for consumers – and may not reflect exactly how applications are deployed in the real world.
Don't hesitate to use the `--producers-by-connection` and `--consumers-by-connection` options to make the runs as close to your workloads as possible.

=== Monitoring

The tool can expose some runtime information on HTTP.
The default port is 8080.
The following options are available:

* `--monitoring`: add a `threaddump` endpoint to display a thread dump of the process.
This can be useful to inspect threads if the tool seems blocked.
* `--prometheus`: add a `metrics` endpoint to expose metrics using the Prometheus format.
The endpoint can then be declared in a Prometheus instance to scrape the metrics.
* `--monitoring-port`: set the port to use for the web server.

[[performant-tool-instance-synchronization]]
=== Synchronizing Several Instances

NOTE: This feature is available only on Java 11 or more.

Instances of the performance tool can synchronize to start at the same time.
This can prove useful when you apply different workloads and want to compare them on the same monitoring graphics.
The `--id` flag identifies the group of instances that need to synchronize and the `--expected-instances` flag sets the size of the group.

Let's start a couple of instances to compare the impact of message size.
The first instance uses 100-byte message:

----
java -jar stream-perf-test.jar --id msg-size-comparison --expected-instances 2 \
                               --size 100
----

The instance will wait until the second one is ready:

----
java -jar stream-perf-test.jar --id msg-size-comparison --expected-instances 2 \
                               --size 200
----

Both instances _must_ share the same `--id` if they want to communicate to synchronize.

The default synchronization timeout is 10 minutes.
This can be changed with the `--instance-sync-timeout` flag, using a value in seconds.

NOTE: Instance synchronization is compatible with https://perftest-dev.rabbitmq.com/#instance-synchronization[PerfTest], the AMQP 0.9.1 performance tool for RabbitMQ: instances of both tools can synchronize with each other.
The 2 tools use the same flags for this feature.

Instance synchronization requires https://en.wikipedia.org/wiki/IP_multicast[IP multicast] to be available.
IP multicast is not necessary when the performance tool runs on Kubernetes pods.
In this case, the tool asks Kubernetes for a list of pod IPs.
The performance tool instances are expected to run in the same namespace, and the namespace must be available in the `MY_POD_NAMESPACE` environment variable or provided with the `--instance-sync-namespace` flag.
As soon as the namespace information is available, the tool will prefer listing pod IPs over using IP multicast.
Here is an example of using instance synchronization on Kubernetes by providing the namespace explicitly:

----
java -jar stream-perf-test.jar --id workload-1 --expected-instances 2 \
                               --instance-sync-namespace qa
----

NOTE: The performance tool needs permission to ask Kubernetes for a list of pod IPs.
This is done by creating various policies e.g. with YAML.
See the https://github.com/jgroups-extras/jgroups-kubernetes[Kubernetes discovery protocol for JGroups page] for more information.

=== Using Environment Variables as Options

Environment variables can sometimes be easier to work with than command line options.
This is especially true when using a manifest file for configuration (with Docker Compose or Kubernetes) and the number of options used grows.

The performance tool automatically uses environment variables that match the snake case version of its long options.
E.g. it automatically picks up the value of the `BATCH_SIZE` environment variable for the `--batch-size` option, but only if the environment variable is defined.

You can list the environment variables that the tool picks up with the following command:

----
java -jar stream-perf-test.jar --environment-variables
----

The short version of the option is `-env`.

To avoid collisions with environment variables that already exist, it is possible to specify a prefix for the environment variables that the tool looks up.
This prefix is defined with the `RABBITMQ_STREAM_PERF_TEST_ENV_PREFIX` environment variable, e.g.:

----
RABBITMQ_STREAM_PERF_TEST_ENV_PREFIX="STREAM_PERF_TEST_"
----

With `RABBITMQ_STREAM_PERF_TEST_ENV_PREFIX="STREAM_PERF_TEST_"` defined, the tool looks for the `STREAM_PERF_TEST_BATCH_SIZE` environment variable, not `BATCH_SIZE`.

=== Logging

The performance tool binary uses Logback with an internal configuration file.
The default log level is `warn` with a console appender.

It is possible to define loggers directly from the command line, this is useful for quick debugging.
Use the `rabbitmq.streamperftest.loggers` system property with `name=level` pairs, e.g.:

----
java -Drabbitmq.streamperftest.loggers=com.rabbitmq.stream=debug -jar stream-perf-test.jar
----

It is possible to define several loggers by separating them with commas, e.g. `-Drabbitmq.streamperftest.loggers=com.rabbitmq.stream=debug,com.rabbitmq.stream.perf=info`.

It is also possible to use an environment variable:

----
export RABBITMQ_STREAM_PERF_TEST_LOGGERS=com.rabbitmq.stream=debug
----

The system property takes precedence over the environment variable.

Use the environment variable with the Docker image:

----
docker run -it --rm --network host \
    --env RABBITMQ_STREAM_PERF_TEST_LOGGERS=com.rabbitmq.stream=debug \
    pivotalrabbitmq/stream-perf-test
----
