== Common Usage

=== Connection

The performance tool connects by default to localhost, on port 5552, with
default credentials (`guest`/`guest`), on the default `/` virtual host.
This can be changed with the `--uris` option:

----
java -jar stream-perf-test.jar --uris rabbitmq-stream://rabbitmq-1:5552
----

The URI follows the same rules as the
https://www.rabbitmq.com/uri-spec.html[AMQP 0.9.1 URI icon:external-link[]^],
except the protocol must be `rabbitmq-stream`.
The next command shows how to set up the different elements of the URI:

----
java -jar stream-perf-test.jar \
  --uris rabbitmq-stream://guest:guest@localhost:5552/%2f
----

The option accepts several values, separated by commas. By doing so, the tool
will be able to pick another URI for its "locator" connection, in case a node
crashes:

----
java -jar stream-perf-test.jar \
  --uris rabbitmq-stream://rabbitmq-1:5552,rabbitmq-stream://rabbitmq-2:5552
----

Note the tool uses those URIs only for management purposes, it does not use them
to distribute publishers and consumers across a cluster.

It is also possible to enable TLS by using the `rabbitmq-stream+tls` scheme:

----
java -jar stream-perf-test.jar \
  --uris rabbitmq-stream+tls://guest:guest@localhost:5551/%2f
----

Note the performance tool will automatically configure the client to trust all
server certificates and to not use a private key (for client authentication).

Have a look at the https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#understanding-connection-logic[connection logic section icon:external-link[]^] of the stream Java client in case of connection problem.

=== Publishing Rate

It is possible to limit the publishing rate with the `--rate` option:

----
java -jar stream-perf-test.jar --rate 10000
----

RabbitMQ Stream can easily saturate the resources of the hardware, it can especially
max out the storage IO. Reasoning when a system is under severe constraints can
be difficult, so setting a low publishing rate can be a good idea to get familiar
with the performance tool and the semantics of streams.

=== Number of Producers and Consumers

You can set the number of producers and consumers with the `--producers` and
`--consumers` options, respectively:

----
java -jar stream-perf-test.jar --producers 5 --consumers 5
----

With the previous command, you should see a higher consuming rate than
publishing rate. It is because the 5 producers publish as fast as they can
and each consumer consume the messages from the 5 publishers. In theory
the consumer rate should be 5 times the publishing rate, but as stated previously,
the performance tool may put the broker under severe constraints, so the numbers
may not add up.

You can set a low publishing rate to verify this theory:

----
java -jar stream-perf-test.jar --producers 5 --consumers 5 --rate 10000
----

With the previous command, each publisher should publish 10,000 messages per second,
that is 50,000 messages per second overall. As each consumer consumes each published messages,
the consuming rate should be 5 times the publishing rate, that is 250,000 messages per
second. Using a small publishing rate should let plenty of resources to the system,
so the rates should tend towards those values.

=== Streams

The performance tool uses a `stream` stream by default, the `--streams` option allows
specifying streams that the tool will try to create. Note producer
and consumer counts must be set accordingly, as they are not spread across the
stream automatically. The following command will run a test with 3 streams, with
a producer and a consumer on each of them:

----
java -jar stream-perf-test.jar --streams stream1,stream2,stream3 \
                               --producers 3 --consumers 3
----

The stream creation process has the following semantics:

* the tool always tries to create streams.
* if the target streams already exist and have the exact same properties
as the ones the tool uses (see <<advance-usage.adoc#performance-tool-retention,retention>> below), the
run will start normally as stream creation is idempotent.
* if the target streams already exist but do not have the exact same properties
as the ones the tool uses, the run will start normally as well, the tool will output a warning.
* for any other errors during creation, the run will stop.
* the streams are not deleted after the run.
* if you want the tool to delete the streams after a run, use the `--delete-streams` flag.

Specifying streams one by one can become tedious as their number grows, so the `--stream-count`
option can be combined with the `--streams` option to specify a number or a range and a stream name
pattern, respectively. The following table shows the usage of these 2 options and the resulting
exercised streams. Do not forget to also specify the appropriate number of producers and
consumers if you want all the declared streams to be used.

[%header,cols=3*]
|===
|Options
|Computed Streams
|Details

|`--stream-count 5 --streams stream`
|`stream-1,stream-2,stream-3,stream-4,stream-5`
|Stream count starts at 1.

|`--stream-count 5 --streams stream-%d`
|`stream-1,stream-2,stream-3,stream-4,stream-5`
|Possible to specify a https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html[Java printf-style format string icon:external-link[]^].

|`--stream-count 10 --streams stream-%d`
|`stream-1,stream-2,stream-3,..., stream-10`
|Not bad, but not correctly sorted alphabetically.

|`--stream-count 10 --streams stream-%02d`
|`stream-01,stream-02,stream-03,..., stream-10`
|Better for sorting.

|`--stream-count 10 --streams stream`
|`stream-01,stream-02,stream-03,..., stream-10`
|The default format string handles the sorting issue.

|`--stream-count 50-500 --streams stream-%03d`
|`stream-050,stream-051,stream-052,..., stream-500`
|Ranges are accepted.

|`--stream-count 50-500`
|`stream-050,stream-051,stream-052,..., stream-500`
|Default format string.

|===

=== Publishing Batch Size

The default publishing batch size is 100, that is a publishing frame is sent every 100 messages.
The following command sets the batch size to 50 with the `--batch-size` option:

----
java -jar stream-perf-test.jar --batch-size 50
----

There is no ideal batch size, it is a tradeoff between throughput and latency.
High batch size values should increase throughput (usually good) and latency (usually not so
good), whereas low batch size should decrease throughput (usually not good) and latency (usually
good).

=== Unconfirmed Messages

A publisher can have at most 10,000 unconfirmed messages at some point. If it reaches this value,
it has to wait until the broker confirms some messages. This avoids fast publishers overwhelming
the broker. The `--confirms` option allows changing the default value:

----
java -jar stream-perf-test.jar --confirms 20000
----

High values should increase throughput at the cost of consuming more memory, whereas low values
should decrease throughput and memory consumption.

=== Message Size

The default size of a message is 10 bytes, which is rather small. The `--size` option lets you
specify a different size, usually higher, to have a value close to your use case. The next command
sets a size of 1 KB:

----
java -jar stream-perf-test.jar --size 1024
----

Note the message body size cannot be smaller that 8 bytes, as the performance tool stores
a long in each message to calculate the latency. Note also the actual size of a message will be
slightly higher, as the body is wrapped in an https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#working-with-complex-messages[AMQP 1.0 message icon:external-link[]^].

[[performance-tool-connection-pooling]]
=== Connection Pooling

The performance tool does not use connection pooling by default: each producer and consumer has its own connection.
This can be appropriate to reach maximum throughput in performance test runs, as producers and consumers do not share connections.
But it may not always reflect what applications do, as they may have slow producers and not-so-busy consumers, so sharing connections becomes interesting to save some resources.

It is possible to configure connection pooling with the `--producers-by-connection` and `--consumers-by-connection` options.
They accept a value between 1 and 255, the default being 1 (no connection pooling).

In the following example we use 10 streams with 1 producer and 1 consumer on each of them.
As the rate is low, we can re-use connections:

----
java -jar stream-perf-test.jar --producers 10 --consumers 10 --stream-count 10 \
                               --rate 1000 \
                               --producers-by-connection 50 --consumers-by-connection 50
----

We end up using 2 connections for the producers and consumers with connection pooling, instead of 20.
