name: Test against RabbitMQ 3.13 stable

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Checkout tls-gen
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Start broker
        run: ci/start-broker.sh
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
      - name: Package Stream Perf Test
        run: ci/package-stream-perf-test.sh
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Delete old releases
        uses: docker://pivotalrabbitmq/delete-release-action:latest
        with:
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          tag-filter: '^v-stream-perf-test-1.[0-9]+.0-SNAPSHOT-[0-9]{8}-[0-9]{6}$'
          keep-last-n: 2
      - name: Push to GitHub Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          files: packages/*
          name: ${{ env.release_name }}
          tag_name: ${{ env.tag_name }}
          target_commitish: main
          prerelease: true
          draft: false
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
      - name: Delete latest release
        uses: docker://pivotalrabbitmq/delete-release-action:latest
        with:
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          tag-filter: '^v-stream-perf-test-latest$'
          keep-last-n: 0
      - name: Make sure latest release is deleted
        run: |
          sleep 5s
      - name: Push to GitHub Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          files: packages-latest/*
          name: stream-perf-test-latest
          tag_name: v-stream-perf-test-latest
          target_commitish: main
          prerelease: true
          draft: false
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
      - name: Trigger Stream Perf Test Docker image build
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: new_release
          client-payload: >-
            {"version": "${{ env.release_version }}",
            "url" : "https://github.com/rabbitmq/rabbitmq-java-tools-binaries-dev/releases/download/v-stream-perf-test-${{ env.release_version }}/stream-perf-test-${{ env.release_version }}.jar",
            "tags": "pivotalrabbitmq/stream-perf-test:dev,pivotalrabbitmq/stream-perf-test:${{ env.release_version }}"}
      - name: Publish Documentation
        run: |
          git config user.name "rabbitmq-ci"
          git config user.email "rabbitmq-ci@users.noreply.github.com"
          ci/publish-documentation-to-github-pages.sh
