name: Test against RabbitMQ alphas

on:
  schedule:
    - cron:  '0 4 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rabbitmq-image: [ 'pivotalrabbitmq/rabbitmq:v4.0.x', 'pivotalrabbitmq/rabbitmq:main' ]
    name:  Test against ${{ matrix.rabbitmq-image }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout tls-gen
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
        env:
          RABBITMQ_IMAGE: ${{ matrix.rabbitmq-image }}
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
