name: Test against RabbitMQ 3.12 stable (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Checkout tls-gen
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
